# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'epamLib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for epamLib

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'epamLibTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'epamLib-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for epamLib-tvOS

  target 'epamLib-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
